name: pdw-sportvenue
app_id: da_K6AIot5UJ3yL
owner: yuumuu
package: sha256:bd6755923cb26d4a5efe526e375a6a11972d1566893819e51e6fd60fc4665d66
debug: true
kind: wasmer.io/App.v0
scaling:
  mode: single_concurrency
volumes:
  - name: payments
    mount: /public/assets/uploads/payments
capabilities:
  database:
    engine: mysql
  locality:
    regions:
      - us-socal1
redirect:
  force_https: true
