[package]
name = "zidanealhakim/sportvenue"
version = "0.1.0"
description = "SportVenue - Booking Lapangan Olahraga"

[commands]
start = "php -S 0.0.0.0:8080 -t public/"

[[volumes]]
name = "data"
dir = "/app/database"

[env]
DB_DRIVER = "sqlite"
DB_SQLITE_PATH = "/app/database/data.db"
