[package]
name = "yuumuu/sportvenue"
version = "0.1.4"
description = "SportVenue - Booking Lapangan Olahraga"

[dependencies]
"php/php" = "*"

[[command]]
name = "run"
module = "php/php:php"
runner = "wasi"

[command.annotations.wasi]
main-args = ["-t", "/app/public", "-S", "0.0.0.0:8080", "/app/public/index.php"]

[[volume]]
name = "data"
dir = "/app/public/assets/uploads/payments"

[[volume]]
name = "database"
dir = "/app/database"

[fs]
"/app" = "."

[env]
DB_DRIVER = "sqlite"
DB_SQLITE_PATH = "/app/database/data.db"
